UWIT-IAM/uw-husky-directory

- husky_directory/app.py
- poetry.lock
- pyproject.toml
- scripts/run-development-server.sh
- tests/conftest.py
- tests/test_app.py
Currently flux won't direct traffic to our instance because it is failing readiness checks. This will fix that.
> Add health and readiness check so flux will allow our instance to be accessible.

- docs/poetry.md
- husky_directory/app.py
- husky_directory/models/search.py
- husky_directory/services/query_generator.py
- husky_directory/services/search.py
- scripts/run-development-server.sh
- tests/services/test_query_generator.py
- tests/services/test_search.py
- tests/test_app.py
This achieves parity+ for name searched compared to the whitepages-ui.
-  Expands model validation for phone number and name.
- Adds services/query_generator.py
- Updates services/search.py to use the query generator
- Updates test_app and test_search
- Adds test_query_generator
> Support multi-name combinatoric queries

- husky_directory/blueprints/search.py
- husky_directory/templates/index.html
- husky_directory/templates/links.html
- husky_directory/templates/results.html
- husky_directory/templates/search.html
Includes small change to backend search, but thing change probably could have been done more efficiently.
> Render search results for a simple query that returns one person (EDS-522 EDS-518).

- husky_directory/templates/results.html
- husky_directory/templates/search.html
- husky_directory/templates/summary_results.html
Addresses
[EDS-533](https://jira.cac.washington.edu/browse/EDS-533)
[EDS-534](https://jira.cac.washington.edu/browse/EDS-534)
[EDS-537](https://jira.cac.washington.edu/browse/EDS-537)
> Enabled Summary and Full results, More button (EDS-533 EDS-534 EDS-537)

- husky_directory/blueprints/search.py
- husky_directory/models/search.py
- husky_directory/services/search.py
- husky_directory/templates/results.html
- husky_directory/templates/summary_results.html
- tests/services/test_search.py
- tests/test_app.py
Model structure now accurately reflects the "Scenario" concept, and no longer requires a dictcomp to translate for the frontend, making it easier to reference and work with.
EDS-541
> Update output model to be more modely

- husky_directory/templates/results.html
- husky_directory/templates/search.html
- Closes [EDS-543](https://jira.cac.washington.edu/browse/EDS-543)
- Minor iterator tweak
> Keeps the search query in the form field (EDS-543), and minor iterator correction

- husky_directory/templates/footer.html
- husky_directory/templates/header.html
- husky_directory/templates/index.html
- husky_directory/templates/links.html
This should fix the following:
> Fix all hrefs to use https instead of http

- husky_directory/templates/full_results.html
- husky_directory/templates/results.html
> minor refactor for full search results (EDS-545)

- husky_directory/templates/index.html
- husky_directory/templates/summary_results.html
Also commented out a script that I think is doing nothing since the id `searchInput` does not exist. Keeping in the code if it is needed for some unknown reason.
> fixed console error, search form and more form had same name

- husky_directory/templates/index.html
> Shows message for no search results (EDS-535)

- husky_directory/models/search.py
- husky_directory/static/js/setSearchNameAttribute.js
- husky_directory/templates/index.html
- husky_directory/templates/search.html
> Search drop down select for criteria Name/Email/Phone etc (EDS-546)

- husky_directory/app.py
- husky_directory/models/pws.py
- husky_directory/models/search.py
- husky_directory/services/search.py
- husky_directory/templates/full_results.html
- tests/services/test_search.py
(Does not yet add support for phone searches, that's next.)
> Adds support for displaying multiple phone numbers by contact type. 

- husky_directory/models/search.py
- husky_directory/services/query_generator.py
- tests/services/test_query_generator.py
Support searching by phone number.
Closes EDS-515
> Add support for phone searches

- husky_directory/blueprints/search.py
- husky_directory/models/pws.py
- husky_directory/models/search.py
- husky_directory/services/query_generator.py
- husky_directory/services/search.py
- husky_directory/templates/dynamic_search_options.html
- husky_directory/templates/index.html
- husky_directory/templates/search.html
- scripts/pre-push.sh
- tests/services/test_search.py
- tests/test_app.py
> [EDS 552] Fix phone number getting chomped during input validation

- husky_directory/services/query_generator.py
- tests/services/test_query_generator.py
…ng every user with a phone number.
> Fix a bug that would submit a blank query to PWS that wound up matching every user with a phone number.

- .gitignore
- husky_directory/models/search.py
- husky_directory/services/query_generator.py
- tests/services/test_query_generator.py
Run this image with:
```
./scripts/run-development-server.sh -i uwitiam/husky-directory:commit-f7a61cfe21
```
> Add support for email queries

- .github/workflows/post-push.yml
...unfortunately the only way to validate this is to actually promote this change.
> Fix promote-deployment workflow to use the right github context variables.

- husky_directory/app.py
- husky_directory/models/base.py
- husky_directory/models/common.py
- husky_directory/models/pws.py
- husky_directory/models/search.py
- husky_directory/services/search.py
- husky_directory/services/translator.py
- tests/blueprints/test_saml_blueprint.py
- tests/blueprints/test_search_blueprint.py
- tests/conftest.py
- tests/services/test_search.py
- tests/services/test_vcard.py
- tests/test_app.py
This is a sub-PR of #51, for the action items: 
>  - [x] Return department in output models (investigating the other issue would be easier if the JSON had that... 😂)
>    - [x] Add a test to determine its inclusion in output models.
It was a medium amount of work that really ought to have been its own jira, but live and learn.
When merged, this will be merged into the EDS-563 branch (which will update that PR), after which I'll work on the remaining action items.
See individual commits for details, I tried to break them out into sensible chunks.
The tl;dr is that department data is now exported and visible via the JSON get:
```
/search?name="cauce"
```
```
// . . . 
"description": "Last name is \"cauce\"", 
"numResults": 1, 
"populations": {
"employees": {
"numResults": 1, 
"people": [
{ …
```
> [EDS-563] Export department and title information in JSON data.

- husky_directory/app.py
- husky_directory/app_config.py
- husky_directory/models/base.py
- husky_directory/models/common.py
- husky_directory/models/pws.py
- husky_directory/models/search.py
- husky_directory/services/pws.py
- husky_directory/services/query_generator.py
- husky_directory/services/search.py
- husky_directory/services/translator.py
- scripts/validate-development-image.sh
- tests/blueprints/test_saml_blueprint.py
- tests/blueprints/test_search_blueprint.py
- tests/conftest.py
- tests/models/test_pws_models.py
- tests/services/test_query_generator.py
- tests/services/test_search.py
- tests/services/test_vcard.py
- tests/test_app.py
Consists of 2 commits, only the first of which actually does the work to support department queries. The follow-up commit increases code coverage and cleans up some cruft. If you are only interested in reviewing the functional changes, please read that commit on its own. This was a pretty small change by comparison to many others.
> [EDS-563] Support department queries

- husky_directory/templates/full_results.html
Display box number just like old directory
closes EDS-555
> [EDS-555] render the box_number on the front end

- husky_directory/app.py
- husky_directory/templates/footer.html
- tests/blueprints/test_search_blueprint.py
> [EDS-587] Make the copyright automatically set to the current year.

- docker/development-server.dockerfile
- husky_directory/gunicorn.conf.py
- husky_directory/models/common.py
- husky_directory/models/pws.py
- husky_directory/services/pws.py
- husky_directory/services/query_generator.py
- husky_directory/services/translator.py
- pyproject.toml
- tests/blueprints/test_search_blueprint.py
- tests/conftest.py
- tests/models/test_common_models.py
- tests/services/test_pws.py
- tests/services/test_search.py
- tests/services/test_translator.py
- tests/services/test_vcard.py
**This change is already running in [dev](https://directory.iamdev.s.uw.edu) as 2.0.1-rc.1**
- Updates gunicorn configuration to work more better
- Optimizes a huge bottleneck in the inbound data pipeline by not translating inbound data into model objects until _after_ filtering the ones we don't want within the scope of a single PWS request.
This is likely as optimized the app layer will get without a significant refactor in data handling and/or a change in the user experience. The biggest issue comes from the auto-generated search queries which result in duplicate data being queried from PWS. This, coupled with the fact that PWS cannot pre-filter certain things for us (i.e., whether or not we can even use the data based on the user's publication status) means that when we generate our …
> Optimization and fine-tuning

- husky_directory/models/pws.py
- pyproject.toml
**Change Description:**
Remove incredibly noisy log statement leftover from implementation debugging.
> Remove incredibly noisy log statement leftover from implementation debugging.

- .github/workflows/deploy.yml
More changes to the deploy action.
This branch successfully ran the deploy action to dev, using the deploy action and specifying dev in the target.
https://github.com/UWIT-IAM/uw-husky-directory/actions/runs/3716770134
**Closes Jira(s)**: 
GH-147
> [GH-147] more changes for github issue 147, tweaking til we get the deploy action right.

- pyproject.toml
**Change Description:**
see above
**Closes GH(s)**: {{ FILL THIS IN }}
GH-159
> Manually update version number to test autodeploy to dev instance (will still require a patch semver guidance)

- .github/workflows/create-release.yml
- pyproject.toml
Change Description:
see above
Closes GH(s): {{ FILL THIS IN }}
https://github.com/UWIT-IAM/uw-husky-directory/issues/159
> [GH-159](again) Fix the manually update version number to test autodeploy to dev instance (will still require a patch semver guidance)Gh 159

- poetry.lock
- pyproject.toml
**Change Description:**  Ran poetry update to update all Python dependencies to their latest compatible versions.
**Closes Github Issue(s)**: [GH-197](https://github.com/UWIT-IAM/uw-husky-directory/issues/197)
**Testing**: 
If you do not do both of these things, your checks will either not run, or have a high probability of failing.
> [GH-197] - Ran poetry update to update dependencies
