- docs/poetry.md
- husky_directory/app.py
- husky_directory/models/search.py
- husky_directory/services/query_generator.py
- husky_directory/services/search.py
- scripts/run-development-server.sh
- tests/services/test_query_generator.py
- tests/services/test_search.py
- tests/test_app.py
- Adds /search endpoint
- Adds PWS client and models
- Adds Directory Search Service and models
- Adds tests
- Slight refactor to app instantiation
- Allows an injector to be passed in from another context in order to provide more control to our testing ecosystem
> Support basic PWS name search as an API call.

- .github/scripts/promote.sh
- .github/workflows/post-push.yml
- docker/development-server.dockerfile
- husky_directory/app_config.py
- husky_directory/blueprints/app.py
- husky_directory/models/search.py
- husky_directory/util.py
- scripts/pre-push.sh
- scripts/run-development-server.sh
- tests/test_app.py
- tests/test_app_config.py
Closes EDS-519
- Adds support for a build id and start time (i.e., tag, commit, etc.) in the health report (similar to identity/healthz)
- Adds a promotion script that logs into docker, re-tags an image, then pushes the resulting image
- Adds a workflow job that will run if the validation step succeeds that executes the promotion script
NB: You can see that in the check suite that ran after [this code was pushed](https://github.com/UWIT-IAM/uw-husky-directory/pull/13/checks?check_run_id=1773701094) that the deploy step was skipped because the branch I pushed to (`EDS-519`) is not `main`. 
[Here](https://github.com/UWIT-IAM/uw-husky-directory/runs/1773467011?check_suite_focus=true) is an example of the script running and pushing a new image (although I changed a couple of values to not …
> [EDS-519] Support automated deployments to dev

- scripts/run-development-server.sh
By default, will keep its current behavior to build an image from the existing code and run that.
You can now supply the `--image/-i` flag to name any image, which will be pulled and run. Useful for testing commits associated with PRs!
e.g., `./scripts/run-development-server.sh -i uwitiam/husky-directory:commit-07428c4d65`
> Make it possible to pull and run any development server image as a one-liner

- husky_directory/models/pws.py
- husky_directory/services/search.py
- husky_directory/settings/logging.yml
- tests/services/test_search.py
Closes EDS-540.
Also:
- Improves query time by only searching for employees (for now), instead of filtering the results after the query.
- Increases query page size to 250
> [EDS-540] Remove duplicate results from search

- husky_directory/templates/index.html
Firefox was complaining that there were no spaces between attributes:
> Fix error in bootstrap css link

- husky_directory/templates/summary_results.html
We have new backend results bringing in multiple phone numbers. For the **summary** results page, this change will show just the `phone` per the old/current directory.
Closes (EDS-550 and EDS-527)
> Modify summary results to show only the 'phone' field.

- husky_directory/app.py
- husky_directory/blueprints/search.py
- husky_directory/models/search.py
- husky_directory/services/query_generator.py
- husky_directory/templates/error_display.html
- husky_directory/templates/index.html
- poetry.lock
- pyproject.toml
- tests/blueprints/test_search_blueprint.py
- tests/services/test_query_generator.py
- tests/services/test_search.py
- tests/test_app.py
Closes EDS-517
- Users can now search by box number
- Adds input validation for box number
- Adds error handling for `/search/render`
- Adds tests for rendered HTML output to cover empty results, bad box number input, and generic 500 error handling
- Slight refactor adds `error_display.html` template to handle both empty results and errors from the server, since the formatting is the same.
You can test this image with: `./scripts/run-development-server.sh -i uwitiam/husky-directory:commit-2dd4779d82` (you may also need to include the `-c` argument if you do not have your `UWCA_CERTIFICATE_PATH` environment variable set up.)
> [EDS-517] Supports box number queries

- husky_directory/app.py
- husky_directory/blueprints/app.py
- husky_directory/blueprints/saml.py
- husky_directory/models/enum.py
- husky_directory/models/search.py
- husky_directory/templates/index.html
- husky_directory/templates/search.html
- scripts/validate-development-image.sh
- tests/blueprints/test_saml_blueprint.py
- tests/conftest.py
Note: Does **NOT** enable student search yet. The radio buttons won't currently have any effect on the search results.
- When a user visits the page, they are now shown the sign in link in order to see other search options.
- After signing in, they can select other search options
- Fixes the mock idp integration so that it works locally and is testable.
- Adds tests!
You can test these changes with:
```
./scripts/run-development-server.sh -i uwitiam/husky-directory:commit-1ebcfc9854
```
> [EDS-556] Supports SAML sign-on to unlock other search options

- docs/logging.md
- docs/manual-deployments.md
- husky_directory/blueprints/saml.py
- Fixes the POST route calling the wrong function
- Fixes an invalid relay state being returned (or rather, not being returned at all)
- Adds some resiliency to relay state redirection.
- Adds some docs for how to deploy manually, and find logs
This change has already been deployed manually and is available to preview at https://uw-directory.iamdev.s.uw.edu.
Again, this won't actually return students i the search, but you should be able to get through the sign-in process.
> Fix the un-mocked SAML flow

- .gitignore
- docker/development-server.dockerfile
- husky_directory/app.py
- husky_directory/app_config.py
- husky_directory/blueprints/saml.py
- husky_directory/models/search.py
- husky_directory/services/pws.py
- poetry.lock
- pyproject.toml
- scripts/pre-push.sh
- tests/conftest.py
- tests/test_app_config.py
Also:
- Fixes "Population" showing up in dropdown field
- Refactors `app_config.py` to modularize settings (like we do for identity); support populating settings from dotenv files.
This doesn't actually do any redis integration or configuring of the sessions at the moment; it only sets up a local filesystem cache, which may or may not work for our dev server. Do not be surprised if the session issue still persists; this is just setting up some scaffolding.
> Adds session support 

- .gitignore
- husky_directory/static/css/body.css
- husky_directory/static/css/mini.css
Closes EDS-536
1. Let Google handle the browser compatibility issues by importing the family directly.
NB: Do you have any idea how hard it is to determine what font types IE10 supports?!
2. Change name to match Google's (`condensed` instead of `compressed`)
3. Remove a pretty glaring broken CSS block.
> Fix EncodeSans font family.

- husky_directory/blueprints/search.py
- husky_directory/models/search.py
- husky_directory/templates/search.html
- husky_directory/templates/search_attribute_selection.html
- husky_directory/templates/search_options.html
- husky_directory/templates/summary_results_table/scenario_population_block.html
- tests/blueprints/test_search_blueprint.py
- tests/conftest.py
- Renames `SearchDirectorySimpleInput` to `SearchDirectoryFormInput`
- Fixes "more" links not always preserving user selections on re-render by adding `render_` override fields to `SearchDirectoryFormInput`, so that the "More" buttons can search one thing, but instruct the server to render another. This gives us parity with the existing directory More behavior. However, see also EDS-566.
- Adds a combinatoric test suite for all possible form options, to verify that in all cases, the resulting page is rendered as we expect. 
With the current combination of parameters for that test, there are 60 total tests generated and run that now all pass. There will be lots more once "Department" is supported and added to the "method" parameter list.
> [EDS-565] Expand automated test cases (which required some bugs to be fixed too!)

- husky_directory/blueprints/search.py
- husky_directory/models/pws.py
- husky_directory/models/search.py
- husky_directory/models/vcard.py
- husky_directory/services/pws.py
- husky_directory/services/search.py
- husky_directory/services/translator.py
- husky_directory/services/vcard.py
- husky_directory/templates/full_results.html
- husky_directory/templates/vcard.vcf.jinja2
- scripts/validate-development-image.sh
- tests/blueprints/test_search_blueprint.py
- tests/conftest.py
- tests/services/test_pws.py
- tests/services/test_search.py
- tests/services/test_vcard.py
Closes EDS-564
See specific commits below for further details.
Broad strokes:
- Adds `/search/person/<token>/vcard` route, where the `/vcard` portion can later be expanded to return `/html` and `/json` results if needed (see also EDS-566).
- Adds "Download vcard" button to the full results template
- When a user clicks the "Download vcard" button, then the vcard is downloaded 🤔
The flask route invokes the `VCardService`, which fetches the person's data from PWS, then translates it into a `VCard` object which, when output as a dict to the jinja2 template engine, generates a vcard based on `vcard.vcf.jinja2`, using the `VCard` model exported dict as the template context.
If that sounded too complicated: It works just like HTML templates, but does for VCF instead.
> [EDS-564] Adds vcard support to the cloud-native directory

- husky_directory/templates/full_results.html
- We'll see occasional duplicates in <title, dept> entries for a person, but that's just the data.
- Format is the same as old dir <title>, <dept>
- Closes EDS-524
> [EDS-524] render department and title in full search results

- husky_directory/services/query_generator.py
- husky_directory/services/search.py
- husky_directory/templates/result_count.html
- tests/services/test_query_generator.py
Fixes EDS-568 🐞
Since the PWS search is intersectional, we can't search both for students and employees in a single query (that only returns 'student employees'). This change adds logic to the QueryGenerator to emit student population queries if the request input dictates students should be included, and if the request is authenticated.
> [EDS-568] Actually query for student data when selected (and auth'd)

- husky_directory/services/translator.py
- tests/conftest.py
- tests/services/test_search.py
This one is pretty straightforward. Enables the box_number output to the frontend for employee `Person`s and adds a test to ensure its inclusion.
Search for any employee at the JSON endpoint to verify, e.g.: `http://localhost:8000/search?population=employees&name=cauce`
```
"people": [
{
"boxNumber": "35xxxx", // it's probably fine to include the real one but meh 
"departments": [
{
"department": "University of Washington", 
"title": "President"
}, 
```
> [EDS-570] Exports box_number to front-end

- husky_directory/templates/summary_results_table/scenario_population_block.html
- parity with old directory
- adds blank table cell in description row of summary results for alignment/border.
- closes EDS-575
> [EDS-575] create blank table cell in description row

- husky_directory/templates/full_results.html
- tests/blueprints/test_search_blueprint.py
- tests/conftest.py
- Some folks won't have a box number, check for the data first, then show/not show.
- Adds tests to cover these conditions
- Closes  EDS-573
> [EDS-573] conditionally show box number

- husky_directory/blueprints/saml.py
- husky_directory/models/search.py
- husky_directory/models/vcard.py
- husky_directory/services/translator.py
- husky_directory/services/vcard.py
- husky_directory/templates/vcard.vcf.jinja2
- tests/services/test_vcard.py
My belief that these codes were against spec was an overly strict interpretation was incorrect, and JP found the documentation to prove it. 
This makes the phone types have [parity with the existing directory](https://github.com/UWIT-IAM/whitepages-ui/blob/master/vcui.c#L372-L406). Tried with our usual folks, plus some random students here and there. 
Closes EDS-572
> [EDS-572] Changes vcard phone types back to those defined in whitepages-ui.

- husky_directory/models/pws.py
- tests/models/test_pws_models.py
Closes EDS-576
This nips the problem in the bud at the source, and converts all name fields on import, so oddly cased names will never be inside our system at all.
For clarity, also removes unused additional 'name' fields in the affiliation listings.
> [EDS-576] ensure all human names are normalized on import from PWS

- husky_directory/app.py
- husky_directory/app_config.py
- husky_directory/templates/full_results.html
- husky_directory/templates/result_count.html
- husky_directory/templates/summary_results_table/scenario_population_block.html
- tests/blueprints/test_search_blueprint.py
- tests/conftest.py
Closes EDS-578 and EDS-571
- Adds anchor headings to `full_results.html`
- Ensure a canonical heading hierarchy on `full_results.html` (change the scenario header to h3, and the person's name to h4). If we really need or want the text size to be at parity, we can change the CSS to reflect this. This way the page is structured correctly.
- Adds anchor references to `result_count.html` links
- Adds anchors to scenario headings in `scenario_population_block.html`, part of the the summary results table.
- Adds a positive and a negative test for the for scenario links and references
> [EDS-578, EDS-571] Generate anchor references and headings

- .github/workflows/scheduled-maintenance.yml
- docker/husky-directory-base.dockerfile
This does not affect the _application image_, which is separate. This is only responsible for keeping dependencies updated. Anytime this workflow is run, it will make dependency updates available to the application on the _application's next build_. 
This gives us status updates in the #iam-bots channel that look like this
👇 
You can see this message yourself at [this link](https://uw-it.slack.com/archives/C9KPNR3TQ/p1619813060024800).
> Add workflow to keep our base image up to date

- .github/actions/calculate-base-fingerprint/action.yml
- .github/scripts/pull-or-build-base.sh
- .github/scripts/set-post-push-workflow-vars.sh
- .github/workflows/post-push.yml
- .github/workflows/scheduled-maintenance.yml
- docker/development-server.dockerfile
- docker/docker-compose.app-with-redis.yaml
- docker/husky-directory-base.dockerfile
- docs/docker.md
- docs/running-the-app.md
- husky_directory/app.py
- husky_directory/app_config.py
- husky_directory/settings/compose-with-redis.dotenv
- poetry.lock
- pyproject.toml
- scripts/pre-push.sh
- scripts/run-development-server.sh
- tests/test_app_config.py
Supports EDS-583, but will not fully resolve it on its own. This will also require a change to gcp-k8 for the full effect to test a redis-backed cache in dev before promoting the same change to eval.
**This change allows the application to use a redis cache if the `FLASK_SESSION_TYPE` environment variable is set to `redis`.** This required a little hackery because the default flask_sessions redis implementation does not cover auth for password-protected redis instances, but it's overall a small change.
Other changes that were inside the blast radius:
- Create a local instance using redis by adding `--with-redis` to your `run-development-server.sh` command.
- Support for using a locally rebuilt base image for cases where dependencies change  (`--rebuild-base`)
- Support fingerprinting the …
> Finishes redis cache configuration

- docs/jinja-templates.md
- husky_directory/app.py
- husky_directory/models/base.py
- husky_directory/models/pws.py
- husky_directory/models/vcard.py
- husky_directory/services/vcard.py
- husky_directory/templates/vcard.vcf.jinja2
- tests/models/test_vcard_models.py
- tests/services/test_vcard.py
Closes EDS-581
- Consume addresses from PWS output
- Add model to convert stringy address into a best-guess vcard-formatted string
- Update vcard template to use whitespace control so the template could look nicer
- Add jinja2 documentation to capture some custom filters, and the things i learned about whitespace control
- Add tests for address formatting
- Add tests for addresses in vcards
> [EDS-581] Add support for addresses in vcard export

- husky_directory/blueprints/search.py
- husky_directory/models/common.py
- husky_directory/models/pws.py
- husky_directory/services/auth.py
- husky_directory/services/pws.py
- husky_directory/services/query_generator.py
- husky_directory/services/search.py
- husky_directory/services/translator.py
- husky_directory/services/vcard.py
- husky_directory/util.py
- tests/blueprints/test_search_blueprint.py
- tests/conftest.py
- tests/models/test_common_models.py
- tests/services/test_auth_service.py
- tests/services/test_pws.py
- tests/services/test_query_generator.py
- tests/services/test_search.py
- tests/services/test_translator.py
- tests/services/test_vcard.py
- tests/test_util.py
Closes EDS-584
This is a bigger change than you'd expect, because the fundamental architecture of the post-request filtering was awkwardly designed (see? It's not just others' code i refactor mercilessly) — as in, it wasn't really designed, and therefore was glued together in several ways that made it difficult to visualize, trace, and update. Now all of our constraints are handled the same way by a central component, as close to the "raw" data as possible.
This fixes the problem by formalizing the post-request filtering into a single standard set of constraints, while also allowing certain queries to apply additional constraints. A constraint is basically a function that tests against the returned data from PWS, allowing us to address things like publication flags for affiliations, as …
> [EDS-584][ICEBERG] Fix bug in search result filtering

- husky_directory/models/search.py
- husky_directory/services/translator.py
- tests/blueprints/test_search_blueprint.py
- tests/conftest.py
Closes EDS-549.
- Adds a `sort_key`/`sortKey` field to the `Person` model
- Sets the `sort_key` to the preferred_last_name if it is set, otherwise the registered_surname, _otherwise_ the display name (extreme edge case)
- When exporting the `DirectoryQueryPopulationOutput` model, sort the list of `people` based on the sort key.
- Adds a test to ensure sorting
- Minor update to tests to modularize the `random_string` function into callable fixture
> [EDS-549]  Sort search results by last name

- .github/scripts/install-build-scripts.sh
- .github/steps/README.md
- .github/steps/scheduled-maintenance/configure-environment.sh
- .github/steps/scheduled-maintenance/context-vars.src.sh
- .github/steps/scheduled-maintenance/create-build-artifact.sh
- .github/steps/scheduled-maintenance/create-pull-request.sh
- .github/steps/scheduled-maintenance/slack-notification.json
- .github/steps/scheduled-maintenance/update-application-image.sh
- .github/steps/scheduled-maintenance/update-dependency-image.sh
- .github/workflows/README.md
- .github/workflows/scheduled-maintenance.yml
- .gitignore
- scripts/get-snapshot-fingerprint.sh
- scripts/run-image-tests.sh
This updates the `scheduled-maintenance` workflow to:
1. Actually update dependencies
2. Test the application against those dependency updates
3. Create a PR (which _for now_ requires human approval) to patch the application version along with any updated dependencies.
4. Factor complex logic out of the yml and into bash scripts for easier testing and debugging
5. Use the new [common build scripts](https://github.com/uwit-iam/common-build-scripts) library to centralize some logic shared with identity.uw.
6. Push the new dependency image for faster builds in the future for the same dependency snapshot.
7. Push the new application image (without a deployment tag) so that it can be tested by others if desired.
This adds a negligible, optional amount of weekly overhead for devs to approve the …
> Productionize maintenance workflow

- husky_directory/blueprints/saml.py
- pyproject.toml
I am going to test this in dev by adding an alternate URL like we have for prod, and ensuring that both work as expected.
> [Possible fix for EDS-592] Ensure the user's original host url propagates through the SAML redirection

- .github/steps/deploy/canvas.json
- .github/steps/deploy/configure-canvas.sh
- .github/steps/deploy/deploy.sh
- .github/steps/deploy/get_slack_notification.sh
- .github/workflows/create-release.yml
- .github/workflows/deploy.yml
- docker/deployment.dockerfile
- docs/deployment.md
- docs/release-process.md
- pyproject.toml
- scripts/deploy.sh
Adds two workflows:
- A `create-release` workflow that creates a new release when we merge into main from a pull request
- A `deploy` workflow that is triggered when a release is created, and pushes that release to dev. Additionally, it can be triggered manually to deploy to eval or prod.
Note that both workflows have only been tested in their dry-run modes; they cannot be further validated until merged in.
> Productionize release workflow

- husky_directory/app.py
- husky_directory/blueprints/saml.py
- husky_directory/logging.py
- husky_directory/settings/logging.yml
- pyproject.toml
- tests/test_logging.py
Closes EDS-560, EDS-542
This creates json logs using a method similar to how we do it in identity.uw, so that stackdriver can parse our logs and not report every one of them as an error. 🙃 
Example output from an authenticated request:
```javascript
{
"severity":"INFO",
"message":"[GET] https://it-wseval1.s.uw.edu/identity/v2/person?display_name=%2Athorogood%2A&employeeAffiliationState=current&page_size=250&verbose=True&constraints=namespace&constraints=predicate&constraints=failure_callback : 200",  // See also EDS-590
"module":"pws",
"line":"pws.py#_get_search_request_output:102",
"request":{
"method":"POST",
"url":"http://localhost:8000/search",
"remoteIp":"172.17.0.1",
"uwnetid":"root"  // This is `root` because of the mock idp running locally which returns the app runas user
}
}
```
> Productionize log configuration

- .github/workflows/pull-request.yml
- husky_directory/app_config.py
- husky_directory/blueprints/saml.py
- husky_directory/settings/base.dotenv
- pyproject.toml
Assuming https://directory-alt.iamdev.s.uw.edu/saml/login works at some point, then this PR fixes the issue. Currently waiting for an issue with SP registry syncing to be resolved. Please don't approve or merge this change unless the issue is resolved without any iterations to this PR.
This change is already running in dev as version 1.2.3-rc.6
> Fix hard-coded ACS url and null RelayState with SAML flow

- husky_directory/blueprints/search.py
- husky_directory/templates/summary_results_table/scenario_population_block.html
- pyproject.toml
- tests/blueprints/test_metrics_blueprint.py
- tests/blueprints/test_search_blueprint.py
- tests/test_app.py
Closes EDS-585
- Updates tests to account for new behavior
- If a user types (or uses a back button) to get to `/search`, they will
be silently redirected back to `/` instead of causing a MethodNotAllowed error.
- Adds a placeholder test for the metrics placeholder (for coverage)
> Remove /search GET endpoint as a json interface.

- husky_directory/templates/summary_results_table/scenario_population_block.html
- pyproject.toml
Fixes a minor issue with student listings where because we don't show student numbers (unless they are also an employee with an employee phone number), the value was being set to None instead of an empty list. The `None` value was being output explicitly, which we didn't want.
so, now we only show a phone number if it has a non-blank value.
> Don't display any output for a phone number if a user's is blank.

- .github/steps/create-release/is-release-required.sh
- .github/workflows/create-release.yml
- .github/workflows/pull-request.yml
- docs/release-process.md
- pyproject.toml
This change allows setting the `semver-guidance:no-bump` label to indicate that a pull request should _not_ result in generating a new version and release. (For instance, when updating docs.)
> Support 'semver-guidance:no-bump' to indicate a PR is a docs-only update

- husky_directory/logging.py
- husky_directory/models/pws.py
- husky_directory/services/pws.py
- husky_directory/services/search.py
- husky_directory/services/translator.py
- pyproject.toml
This isn't my prettiest work, but it'll help us with our optimizations.
Our request timers now include the following information: 
```javascript
{
"query": {
"name": "thom",
"population": "all",
"includeTestIdentities": false
},
"statistics": {  // NEW!
"numPagesReturned": 18,
"numResultsIgnored": 1429,
"numResultsReturned": 2633,
"numUserSearchTokens": 1,
"numQueriesGenerated": 10,
"numDuplicatesFound": 422
},
"timer": {
"name": "search_directory",
"timerResult": 3.537,
"startTime": 1631832347.8775764,
"endTime": 1631832351.4141982
}
}
```
> Export additional statistics when logging timer contexts.

- husky_directory/models/search.py
- pyproject.toml
- tests/models/test_search_models.py
Closes EDS-605 and future proofs against a couple of other whitespace possibilities. Adds tests.
> [EDS-605] Fixes for whitespace handling in user submissions

- .github/workflows/create-release.yml
This is currently blocking things deploying to dev. (We didn't find out sooner because our automation has been turned off the past couple of days during the flux upgrade.)
> Fix release workflow no longer being compatible with a previous update

- husky_directory/app.py
- husky_directory/blueprints/search.py
- husky_directory/models/pws.py
- husky_directory/models/search.py
- husky_directory/services/query_generator.py
- husky_directory/services/translator.py
- pyproject.toml
- tests/blueprints/test_search_blueprint.py
- tests/models/test_pws_models.py
- tests/models/test_search_models.py
- tests/services/test_query_generator.py
- tests/test_app.py
- Supports 2-character name queries (first iteration) [EDS-599]
- Enforces 3-character queries for all other fields
- Improves surname resolution when determining sort keys 
- Improves error messages seen by users
**Closes Jira(s)**: EDS-599
> [EDS-599] Support 2-character name searches, plus other fixes!

- .github/steps/scheduled-maintenance/context-vars.src.sh
- .github/workflows/README.md
- docs/deployment.md
- scripts/deploy.sh
**Change Description:**
Updates how we tag our docker images so that our automation workflows can integrate safely with Flux v2
> Fix the "semver-date" strings which are not lexicographically sortable.

- .github/steps/create-release/is-release-required.sh
- .github/steps/create-release/push-release-image.sh
- .github/workflows/create-release.yml
- scripts/update-dependency-image.sh
- Fixes release job using wrong variable for new image version
- Ensures that an error in the configuration job will fail the build
- Ensures that when releasing, we update the `:latest` tag for our dependency image.
[Dry run succeeded](https://github.com/UWIT-IAM/uw-husky-directory/runs/3677801477?check_suite_focus=true)
> Fix several issues with the create-release workflow.

- .github/steps/create-release/is-release-required.sh
- .github/steps/create-release/push-release-image.sh
- .github/workflows/create-release.yml
- scripts/get-snapshot-fingerprint.sh
- scripts/pre-push.sh
- scripts/update-dependency-image.sh
(Simpler, but more lines of code, because it's easier to understand and better documented.)
Lately a lot of work has gone into the deploy process, but the release process represented in automation
hasn't really caught up. As a result, some old ideals were being used which were causing
release images to be built without the properly set variables.
This update simplifies the workflow by separating the "github release" from the "docker push".
Doing so, we no longer have to try and resolve a pull-request as part of this workflow,
and instead check out the release tag when creating the docker image.
This saves us from accidentally introducing drift in what is released vs. what is running,
and unifies the process using the already ubiquitous `pre-push.sh`.
to the right …
> Use a simpler approach to create and push release images.

- .github/workflows/create-release.yml
- .github/workflows/deploy.yml
A race condition previously allowed the 'deploy' step to run before the image was actually pushed to GCR. I Remedied that by moving the deploy step into the create-release workflow.
Also, added gcr login step to the job that pushes to docker, which I forgot before but couldn't test because of dry runs.
> Another small fix/tweak for the release workflow

- docker/deployment.dockerfile
- husky_directory/gunicorn.conf.py
- poetry.lock
- pyproject.toml
Load testing against dev using `gthread`, `eventlet`, and `gevent` revealed gevent to be the best choice for this application, with a ~7% reduction in errors when running at/near the CPU limit for the cluster.
> Use `gevent` as our gunicorn worker type

- husky_directory/services/translator.py
- pyproject.toml
- tests/blueprints/test_search_blueprint.py
> [EDSI-615] Fix 'Phone: None' appearing in full listings of student searches

- husky_directory/models/search.py
- pyproject.toml
- tests/models/test_search_models.py
- Searches for `lastname, firstname` will work now. This is now an "undocumented feature" which is better than an "accidental regression," but I created EDS-617 for a future iteration to actually document this for users.
**Closes Jira(s)**: EDS-615, EDS-616
> [EDS-616] Support "lastname, firstname" searches

- husky_directory/static/css/body.css
**Change Description:** The CSS we "stole" from the old product had a display bug in it. This fixes it. I'm not even bumping the version for this.
**Closes Jira(s)**:  EDS-623
> Prevent submit button text from turning invisible when focused.

- husky_directory/models/pws.py
- husky_directory/models/transforms.py
- husky_directory/services/name_analyzer.py
- husky_directory/services/reducer.py
- husky_directory/services/translator.py
- husky_directory/services/vcard.py
- pyproject.toml
- tests/models/test_pws_models.py
- tests/services/test_reducer.py
**Change Description:** Moves name analysis out of the model and into a separate class that can be invoked as needed. This prevents the actual display name from ever being manipulated, which has the intended side effect of displaying the user's actual display name, instead of something uncannily similar, but not quite their name.
**Closes Jira(s)**: [IAMTEAM-111](https://jira.cac.washington.edu/browse/IAMTEAM-111)
> [IAMTEAM-111] Fix users' display name casing being mangled during lexical analysis

- husky_directory/app_config.py
- husky_directory/blueprints/search.py
- husky_directory/models/common.py
- husky_directory/templates/search.html
- pyproject.toml
- tests/blueprints/test_search_blueprint.py
**Change Description:** Now, if a user last selected "full" details of a search, their next visit will default to "full", and vice-versa (although "vice-versa" is the default behavior).
**Closes Jira(s)**: EDS-14
> [EDS-14] Use a preferences cookie to retain the last set response detail

- husky_directory/blueprints/app.py
- pyproject.toml
- tests/test_app.py
**Change Description:** Change `/health` to `/status`
**Closes Jira(s)**: EDS-602
> [EDS-602] Change /health to /status

- husky_directory/app.py
- husky_directory/app_config.py
- husky_directory/services/object_store.py
- husky_directory/services/query_synchronizer.py
- husky_directory/services/search.py
- pyproject.toml
- tests/blueprints/test_search_blueprint.py
- tests/services/test_object_store.py
- tests/services/test_query_synchronizer.py
- tests/services/test_reducer.py
- tests/test_app.py
- tests/test_app_config.py
**Change Description:**
In short, this protects us from button mashing the "search" button. When a user searches, we calculate a deterministic id for the query. When the query completes, we cache the results for a very short amount of time. If the user interrupts the initial request by searching again, or even if another user happens to try the same search at the same time, the subsequent searches will subscribe to the results of the first, ongoing query, rather than query PWS and parse the results again themselves.
This should drastically reduce the number of resources used while processing large response sets.
**Closes Jira(s)**: EDS-631
> [EDS-631] Prevents long queries from consuming duplicate resources if queries are resubmitted by users

- poetry.lock
- pyproject.toml
- scripts/build-layers.sh
**Change Description:** Currently the cache is not taking into account any build args, which means that after a workflow updates the branch to have a new version, the old version string is still cached in the image. This ensures that if the build args cahnge for the app image, the image is rebuilt using the correct environment args.
- ~[ ] I have run `poetry run tox`~
> Pass build args as salt when building the app layer so that the version matches poetry

- scripts/get-deployed-version.sh
Change the `target_version` from `'"<version>"'` to `<version>` - allows deployment notification to succeed, unblocking the rest of the deployment
It worked here https://github.com/UWIT-IAM/uw-husky-directory/actions/runs/3832480478/jobs/6522833559#step:5:43
**Closes GH Issues(s)**: 
GH-155
> [GH-155] update version retrieval for deploy to eval (a promotion from dev to eval)

- .github/steps/create-release/is-release-required.sh
- .github/steps/deploy/configure-canvas.sh
- .github/steps/pull-request/create-pr-tag.sh
- .github/workflows/deploy.yml
- scripts/deploy.sh
See above. Right now, we only get warnings, but soon they will generate failures.
**Closes GH(s)**:
GH-163
There are scripts in the actions repo that also affect this flow, those will be addressed separately.
More info here
https://github.com/UWIT-IAM/uw-idp-web-tests/issues/29. https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> [GH-163] replace the deprecated 'set-output' with GITHUB_OUTPUT

- .github/actions/configure-docker/action.yml
- .github/workflows/pull-request.yml
- husky_directory/models/search.py
- pyproject.toml
**Change Description:**  This PR fixes a bug in the `b64_encode_href` method of the Person model that caused double Base64 encoding of the `href` when navigating back in the browser. Changes I've made:
1. **Updated `b64_encode_href` validator**:
- The method now checks if the `href` is already Base64 encoded before encoding it again, preventing the double encoding issue.
2. **Github Actions**:
- Automated tests were failing due to outdated dependencies.
- Switched to using pipx for installing Poetry and updated the Google dependencies.
**Closes Github(s)**: [GH-165](https://github.com/UWIT-IAM/uw-husky-directory/issues/165)
> [GH-165] - Prevent double Base64 encoding of profile href + Github Actions updates

- husky_directory/models/enum.py
- husky_directory/models/pws.py
- husky_directory/services/pws.py
- husky_directory/settings/base.dotenv
- husky_directory/settings/compose-with-redis.dotenv
**Context**: During a recent live session, we encountered an issue with the `PWS_HOST` configuration while running locally. The following was observed:
1. Using `PWS_HOST=https://it-wseval1.s.uw.edu` consistently resulted in `500` errors.
2. Switching to `PWS_HOST=https://wseval.s.uw.edu` resolved the issue, and the application worked as expected.
After doing some research I found a change that took effect in EWS EVAL environments on 5/25/23. Any configurations or bookmarks still pointing to the old endpoint will no longer work.
This PR updates the `PWS_HOST` value in the `settings/*.dotenv` files to reflect the current configuration for the EWS EVAL environments. The old endpoint `https://it-wseval1.s.uw.edu` consistently caused 500 errors during local testing. …
> [GH-167] - Update PWS_HOST with new value from REQ7051889

- .github/workflows/create-release.yml
**Change Description:** This PR fixes issues with the `create-release.yml` workflow by making the following updates:  
1. **Installations and Setup:**  
-  Setting up Python 3.10 using `actions/setup-python@v4`.
-  Installing Poetry manually with `pip`
2. **Command Fixes:**  
- Adjusted the `tox` command to include `--` for passing additional arguments correctly, addressing a Poetry behavior where `--` is eaten if not explicitly included.  Reference: [Stack Overflow link for Poetry and Tox argument handling](https://stackoverflow.com/questions/75056352/poetry-tox-how-to-pass-arguments-to-commands-via-tox-when-running-in-poetry).
3. **Other Minor Adjustments:**  
- Added names to a few steps for better clarity.
- Added `workflow_dispatch` to allow manual triggering of the workflow. …
> [GH-169] Fix create-release.yml Workflow Issues and Update Poetry Tox Command Syntax

- husky_directory/models/search.py
- husky_directory/models/vcard.py
- husky_directory/services/translator.py
- husky_directory/services/vcard.py
- husky_directory/templates/full_result.html
- husky_directory/templates/summary_results_table/scenario_population_block.html
- husky_directory/templates/vcard.vcf.jinja2
- pyproject.toml
- tests/services/test_translator.py
- tests/services/test_vcard.py
**Change Description:** This PR addresses the discussion in the Service team meeting on 1/27/2025 regarding email display. The following changes have been made:
- **For employees**: Previously, only the first email (index 0) in the array of emails was shown. Now, all available employee emails are displayed.
- **For students**: Remains the same, only the single directory listing email is displayed, as students have only one email.
- **Email preference**: Remains the same. If both student and employee emails exist, employee emails are prioritized over student emails and takes precedence.
- **vCard support for multiple emails**: The vCard now supports multiple email addresses for employees, displaying all available emails rather than just one.
For more details, refer to the GitHub issue …
> [GH-174] - Allow all "whitepages email addresses" to appear for users on all screens

- .github/pull_request_template.md
**Change Description:** To align templates and processes between Directory and other repos, this PR introduces minor language changes to the pull request template. It removes outdated JIRA reference, replacing it with GitHub, and adds a checklist item to make sure a GitHub issue is attached to the PR.
**Closes Github(s)**: [GH-177](https://github.com/UWIT-IAM/uw-husky-directory/issues/177)
> [GH-177] - Update `pull_request_template.md`

- husky_directory/static/css/body.css
- husky_directory/static/css/print.css
- husky_directory/templates/base.html
- husky_directory/templates/full_result.html
- husky_directory/templates/full_results.html
- husky_directory/templates/links.html
- husky_directory/templates/result_count.html
- husky_directory/templates/search_options.html
- husky_directory/templates/summary_results_table/base.html
- husky_directory/templates/summary_results_table/scenario_population_block.html
- pyproject.toml
- tests/blueprints/test_search_blueprint.py
**Change Description:** This PR includes minor UI tweaks and improvements, with the main changes being:
**Full View**: I switched to using cards for each record to make them easier to distinguish. This also **improved printing by separating the records**. I also fixed inconsistent margins and padding, so you can see more on the screen before needing to scroll.
Checked the card colors for accessibility and it passed: 
**Summary View**: Just like the full view, I fixed inconsistent margins and padding and tightened the rows, so that users can see more results before scrolling. The new view also shows multiple emails for a single person, before, only one was displayed.
I've renamed a few `IDs` and properties for better readability and moved all print-related CSS into the `print.css` file. …
> [GH-182] - Improved search results UI, CSS Refactoring and Cleanup

- husky_directory/templates/summary_results_table/scenario_population_block.html
- pyproject.toml
**Change Description:** If a person doesn't have an office/landline number in `data['phone_contacts']['phones']`, we should display their first mobile number from `data['phone_contacts']['mobiles']` instead. The goal for the summary view is to show a contact number when available, with preference given to landline numbers when present. Users can view all other available phone numbers by clicking 'more' on the summary view or switching to full view mode.
**Closes Github Issue(s)**: [GH-188](https://github.com/UWIT-IAM/uw-husky-directory/issues/188)
**UW Connect Request**: REQ11008424
**Testing Checklist**:
**Note**: This PR is deployed to our `dev` instance.
If you do not do both of these things, your checks will either not run, or have a high probability of …
> [GH-188] - Add mobile phone number to summary search result
